apiVersion: v1
kind: Service
metadata:
  name: padhal-api
  namespace: padhal
spec:
  selector:
    app: padhal-api
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP
