apiVersion: v1
kind: Service
metadata:
  name: padhal-frontend
  namespace: padhal
spec:
  selector:
    app: padhal-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
