apiVersion: apps/v1
kind: Deployment
metadata:
  name: padhal-frontend
  namespace: padhal
  labels:
    app: padhal-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: padhal-frontend
  template:
    metadata:
      labels:
        app: padhal-frontend
    spec:
      containers:
        - name: padhal-frontend
          image: kumsub/padhal-frontend:replace-me
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
