apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: padhal
resources:
  - namespace.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
