services:
  redis:
    image: redis:7-alpine
    container_name: padhal-redis
    ports:
      - "6379:6379"

  api:
    image: padhal-api:local
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    pull_policy: never
    container_name: padhal-api
    environment:
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    image: padhal-frontend:local
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    pull_policy: never
    container_name: padhal-frontend
    ports:
      - "8080:80"
    depends_on:
      - api
