apiVersion: v1
kind: Service
metadata:
  name: {{ include "padhal.frontendName" . }}
  labels:
    {{- include "padhal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "padhal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
