global:
  imageTag: ""
  imagePullPolicy: Always

nameOverride: ""
fullnameOverride: ""

frontend:
  replicaCount: 2
  image:
    repository: kumsub/padhal-frontend
    tag: ""
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

api:
  replicaCount: 2
  image:
    repository: kumsub/padhal-api
    tag: ""
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

redis:
  enabled: true
  replicaCount: 1
  image:
    repository: redis
    tag: 7-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
          service: frontend
          port: 80
        - path: /api
          pathType: Prefix
          service: api
          port: 8000
  tls: []
